spring:
  thymeleaf:
    cache: false # 关闭thymeleaf缓存
    # 数据源配置
  profiles:
    active:
      dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.96.6.135:3308/pet_care?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  mail:
    host: smtp.qq.com
    username: jinke12138@foxmail.com
    password: uynuhfduimuzbbai
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465


#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: au.edu.sydney.web.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

# 日志级别，会打印sql语句
logging:
  level:
    sydney.edu.au.web.mapper: debug

pet-care:
  jwt:
    config:
      secretKey: pet-care # jwt token secret key
      expires: 604800 # unit second ，seven daysVerCodeGenerateUtil
server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
